server:
  port: 9999
  context-pay: /pay
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/interview
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql